name: jrpn15_build
description: Jovial RPN 15C, a calculator simulator inspired by the HP-15C Scientific Calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.18+34    # See also lib/generic_main.dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jrpn:
      git:
        url: https://github.com/zathras/jrpn.git
        path: .
        ref: main

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  msix: ^3.16.0

flutter_launcher_icons:
  image_path: assets_15/icon256.png
  image_path_ios:  assets_15/icon_ios.png
  adaptive_icon_foreground: "assets_15/icon_adaptive.png"
  adaptive_icon_background: "#dbdad1"
  android:
    generate: false
  macos:
    generate: false
    image_path: assets_15/macos_icon.png
  linux:
    generate: false
  windows:
    generate: false
  ios:
    generate: true
  # If changed, "dart run flutter_launcher_icons"
  # See https://pub.dev/packages/flutter_launcher_icons

flutter:
  uses-material-design: true
  fonts:
    - family: KeyLabelFont
      fonts:
          - asset: packages/jrpn/fonts/deja_vu_sans.ttf
            style: normal
            weight: 400
          - asset: packages/jrpn/fonts/deja_vu_sans_bold.ttf
            style: normal
            weight: 700
    - family: LogoFont
      fonts:
        - asset: packages/jrpn/fonts/WorkSans-Regular.ttf
          style: normal
          weight: 400
        - asset: packages/jrpn/fonts/WorkSans-Medium.ttf
          style: normal
          weight: 500
    - family: LiberationMono
      fonts:
        - asset: packages/jrpn/fonts/LiberationMono.ttf
          style: normal
          weight: 400

# "flutter pub run msix:create"
msix_config:
  architecture: x64
  store: true
  display_name: JRPN 15C
  publisher_display_name: Jovial Software
  identity_name: 15297JovialSoftware.jrpn15
  publisher: CN=8C283FE0-3A16-4021-946B-3EF54C23339D
  msix_version: 2.1.18.0
  logo_path: assets_15/windows_icon.png
  file-extension: .15c, .j15c
  execution_alias: jrpn15
