name: jrpn15
base: core18
version: '2.1.11'
summary: Calculator simulator inspired by the HP-15C Scientific Calculator
description: |
  Calculator simulator inspired by the HP-15C scientific calculator.
  Written in Flutter, so UI scales to any screen size, and the same
  code is used for versions for Android, MacOS and Windows.
  store.

grade: stable # must be 'stable' to release into candidate/stable channels

architectures: 
  - build-on: amd64 
  - build-on: arm64

slots:
    dbus-jrpn15:
        interface: dbus
        bus: session
        name: com.jovial.jrpn15

confinement: strict

build-packages:
    - dirmngr

apps:
    jrpn15:
        command: jrpn15
        extensions: [flutter-master]
        plugs:
        - home
        slots:
        - dbus-jrpn15

parts:
    jrpn15:
        plugin: flutter
        source: .
        flutter-target: lib/main.dart
